name: Build YouTube Music AppImage

on:
  push:
    branches: [ master ]
  pull_request:

env:
  NODE_VERSION: "22.x"

jobs:
  build-appimage:
    name: Build AppImage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Add remote, fetch, and merge feature branch
        run: |
          git remote add johannes https://github.com/Johannes7k75/youtube-music.git
          git fetch johannes
          # The following command now includes the flag to allow merging unrelated histories
          git merge johannes/feat/api-websocket --no-ff --no-edit --allow-unrelated-histories
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build AppImage
        env:
          # The GH_TOKEN is often required by release scripts to interact with GitHub
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm release:linux

      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTube-Music-AppImage
          path: |
            dist/*.AppImage
            !dist/*-arm64.AppImage
